version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672" # RabbitMQ management UI
      - "5672:5672"   # RabbitMQ message broker
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  account-manager:
    build:
      context: ./dtu-pay-account-manager
      dockerfile: Dockerfile
    container_name: account-manager
    ports:
      - "8081:8080"

  facade:
    build:
      context: ./dtu-pay-facade
      dockerfile: Dockerfile
    container_name: facade
    ports:
      - "8082:8080"

  payment-service:
    build:
      context: ./dtu-pay-payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "8083:8080"

  report-service:
    build:
      context: ./dtu-pay-report-service
      dockerfile: Dockerfile
    container_name: report-service
    ports:
      - "8084:8080"

  token-manager:
    build:
      context: ./dtu-pay-token-manager
      dockerfile: Dockerfile
    container_name: token-manager
    ports:
      - "8085:8080"

networks:
  default:
    driver: bridge